name:  daves-bumpers
title:  Dave's Bumpers
version: "1.0.0"
summary:    The object is to get the blue ball into a green box. That’s it!
description: |
  How? You hit the ball and it will roll until it hits a bumper or rolls off the grid. (You don’t want it to roll off the grid:) It’s just that simple. It looks easy. It plays easy. It must be easy…………or maybe not. Further instructions are included with the game.

grade: stable
icon: daves-bumpers_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  daves-bumpers:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files (x86)/Daves Bumpers/Bumpers.exe"
      INSTALL_EXE: "$SNAP/InstBump.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

